# Generated by Django 4.2.18 on 2025-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_announcer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_date', models.DateField()),
                ('last_run_time', models.TimeField()),
            ],
        ),
    ]
