# Generated by Django 5.2.17 on 2026-09-23 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_announcer', '0002_lastrun'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short label to tell configurations apart.', max_length=100, verbose_name='Name')),
                ('division', models.PositiveSmallIntegerField(default=1, help_text='Corporation wallet division to read (1-7).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Wallet Division')),
                ('channel_id', models.PositiveBigIntegerField(help_text='Numeric Discord channel ID to post the announcement to.', verbose_name='Discord Channel ID')),
                ('time_delta', models.PositiveIntegerField(default=12, help_text='How many hours of sales history to include per announcement.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lookback (hours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last sent at')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_announcer_configs', to='eveonline.evecorporationinfo', verbose_name='Corporation')),
            ],
            options={
                'verbose_name': 'Announcer Configuration',
                'verbose_name_plural': 'Announcer Configurations',
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='LastRun',
        ),
    ]
