# Generated by Django 5.2.17 on 2026-09-23 11:45

import discord_announcer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_announcer', '0004_rename_last_sent_at_announcerconfig_last_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcerconfig',
            name='time_delta',
            field=models.PositiveIntegerField(default=discord_announcer.models.default_interval, help_text='Posts every this many hours, covering the sales since the previous post. At least one hour.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval (hours)'),
        ),
    ]
