# Generated by Django 5.2.17 on 2026-09-25 08:19

import discord_announcer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_announcer', '0005_time_delta_default_from_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcerconfig',
            options={'default_permissions': (), 'verbose_name': 'Announcer configuration', 'verbose_name_plural': 'Announcer configurations'},
        ),
        migrations.AddField(
            model_name='announcerconfig',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last attempt at'),
        ),
        migrations.AddField(
            model_name='announcerconfig',
            name='last_transaction_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Last transaction seen'),
        ),
        migrations.AlterField(
            model_name='announcerconfig',
            name='channel_id',
            field=models.PositiveBigIntegerField(help_text='Numeric ID of the channel to post to. Enable Developer Mode in Discord, then right-click the channel → "Copy Channel ID".', verbose_name='Discord channel ID'),
        ),
        migrations.AlterField(
            model_name='announcerconfig',
            name='division',
            field=models.PositiveSmallIntegerField(default=1, help_text='Corporation wallet division to read (1-7).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Wallet division'),
        ),
        migrations.AlterField(
            model_name='announcerconfig',
            name='time_delta',
            field=models.PositiveIntegerField(default=discord_announcer.models.default_interval, help_text='How often this configuration posts, in hours. Each post covers the sales since its previous run. At least one hour.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval (hours)'),
        ),
    ]
